wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.33.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1709085355.846296
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 103
      3:
      - 23
      4: 3.10.4
      5: 0.16.3
      6: 4.33.3
      8:
      - 2
      - 5
      13: linux-x86_64
